"""Run Agent 1 (the analyst) on a source CSV and emit the inferred dictionary.

    python -m cli.run_analyst --source data/EFAS0042.csv --table EFAS0042

Writes <table>_inferred_dictionary.json and .md next to the source.
The agent never reads the answer key — everything is inferred from data.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from engine import config  # noqa: F401  (loads .env)
from engine.agents.analyst import analyze, sql_library
from engine.agents.contracts import TableInsight
from engine.staging import Warehouse


def to_markdown(t: TableInsight) -> str:
    lines = [f"# {t.table} — inferred data dictionary",
             f"_Generated by the analyst agent ({t.generated_by}) from data alone — no domain knowledge, no answer key._",
             "", "## Overview"]
    lines += [f"- {s}" for s in t.summary]
    lines += ["", "## Columns", "",
              "| Column | Inferred type | Role | Populated | Distinct | Notes |",
              "|--------|---------------|------|-----------|----------|-------|"]
    for c in t.columns:
        note = " ".join(c.hypotheses) or (c.observations[0] if c.observations else "")
        sent = f" Sentinel {c.sentinels}." if c.sentinels else ""
        lines.append(
            f"| {c.name} | {c.inferred_type} | {c.role} | {c.populated_fraction:.0%} "
            f"| {c.distinct_count} | {note}{sent} |"
        )
    if t.dependencies:
        lines += ["", "## Conditional-population patterns"]
        lines += [f"- {d.statement}" for d in t.dependencies]
    if t.linked_groups:
        lines += ["", "## Linked column groups (fill in together)"]
        lines += [f"- {{{', '.join(g)}}}" for g in t.linked_groups]
    if t.dq_rules:
        lines += ["", "## Data-quality rule library (executable — see the .sql file)",
                  "", "| Rule | Category | Scope | Result | Samples |", "|---|---|---|---|---|"]
        for r in t.dq_rules:
            res = f"**{r.failed}/{r.total} fail**" if r.failed else f"{r.total} pass"
            lines.append(f"| {r.name} | {r.category} | {', '.join(r.columns)} "
                         f"| {res} | {', '.join(r.samples) or '—'} |")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", required=True)
    ap.add_argument("--table", default=None)
    ap.add_argument("--warehouse", default="data/warehouse.duckdb",
                    help="DuckDB staging store (persists staged tables)")
    args = ap.parse_args()

    wh = Warehouse(args.warehouse)
    insight = analyze(args.source, args.table, warehouse=wh)
    src = Path(args.source)
    stem = (args.table or src.stem)
    (src.parent / f"{stem}_inferred_dictionary.json").write_text(
        json.dumps(insight.model_dump(), indent=2, default=str), encoding="utf-8")
    (src.parent / f"{stem}_inferred_dictionary.md").write_text(to_markdown(insight), encoding="utf-8")
    (src.parent / f"{stem}_dq_rules.sql").write_text(sql_library(insight), encoding="utf-8")
    print(f"  DQ rule library: {insight.dq_summary.get('rules_total', 0)} rules "
          f"({insight.dq_summary.get('rules_failing', 0)} failing) -> {stem}_dq_rules.sql")
    print(f"analyst done ({insight.generated_by}) -> {stem}_inferred_dictionary.[json|md]")
    print(f"staged tables in {args.warehouse}: {wh.list_tables()}")
    print("\n".join(f"  - {s}" for s in insight.summary))
    wh.close()


if __name__ == "__main__":
    main()
